### ISSUE TITLE
MQTT Agent Overwrites Task Notifications

### ISSUE THREAD

**Issue by tombresson** [aws/amazon-freertos#231]
**Describe the bug**
MQTT Agent (through the Shadow Client) clears/sets Task Notifications of the task using the library. This causes tasks that rely on task notifications for functionality to exhibit undesired behavior.

This issue was discovered when trying to communicate via a Task Notification, in the Shadow Delta Callback context, to the task managing the Shadow Client. The notification of the task is overwritten by the MQTT Agent to serve it's own purpose.

It is not obvious when calling into these libraries that the MQTT Agent will be using the task's notification for functionality outside of what may have been designed.

The issue may not even manifest in a significantly noticeable fashion, as the setting and clearing of the task notification only happens when calls are made to the MQTT agent. If the right timing conditions occurred, Task Notifications to the calling task (from tasks other than the MQTT Task) could be wiped out.

**System information**
N/A (All)

**Expected behavior**
Library under the hood should not use task notifications for internal functionality. Another **self-contained method of synchronization/feedback** should be employed to avoid commandeering the task notifications of tasks that call into the Shadow and MQTT libs.

This will avoid conflicts with task notifications for tasks that employ them.

**Additional context**

The lines related to task notifications are listed below. 

https://github.com/aws/amazon-freertos/blob/4d6a8a07c6d30a61372d00377a8974658c88e2d9/lib/mqtt/aws_mqtt_agent.c#L1238-L1259

https://github.com/aws/amazon-freertos/blob/4d6a8a07c6d30a61372d00377a8974658c88e2d9/lib/mqtt/aws_mqtt_agent.c#L1666-L1675

**Comment by gordonwang0** [comment]
Hi @tombresson,

The new MQTT library available on the release-1.5 branch no longer uses task notifications.

We have implemented a backwards-compatibility layer to allow applications written for the v1 MQTT library to still work. This layer translates v1 MQTT API calls to v1.5 calls. Since it uses the v1.5 MQTT library underneath, this provides a way to use the v1 API without interfering with task notifications. Please give this a look.

I am closing this issue; please reopen if you have any questions.
