### ISSUE TITLE
MQTTAgentConnectParams_t and iot_defender startInfo.pClientIdentifier different types

### ISSUE THREAD

**Issue by YTvW** [aws/amazon-freertos#2360]
**Describe the bug**
when using clientcredentialIOT_THING_NAME for both MQTTAgent and iot_defender the types don't match
MQTTAgent expects it to be _const uint8_t *_  and iot_defender expects it to be _const char *_ 

**System information**
- ESP32
- VSCode
- MacOS
- form master
- Custom Application, MQTT|, Shadow| ,Greengrass|, OTA|, Device Defender

**Expected behavior**
being able to use the same clientId definition 

**Screenshots or console output**
```
SW/aws-freertos/libraries/c_sdk/aws/defender/src/aws_iot_defender_v1.c:163:33: error: pointer targets in assignment differ in signedness [-Werror=pointer-sign]
     startInfo.pClientIdentifier = clientcredentialIOT_THING_NAME;
```

**Comment by yanjos-dev** [comment]
Hello @YTvW, if I'm understanding correctly, you are using the MQTT Agent with the shim layer of the defender library. If you are using the MQTT Agent, then the client identifier will need to be type `const uint8_t *`. The issue is that the shim layer for the Defender library utilizes v2.x.x of the MQTT API which requires type `const char *` for the client identifier. 

Have you considered explicitly type casting `const char *` to `const uint8_t *`?  It could look something like this:
`MQTTAgentConnectParams_t exVar;`
`exVar.pucClientId = (const uint8_t *) clientcredentialIOT_THING_NAME;`

Alternatively, you could use v2.x.x of the MQTT API so that the type for the client identifier are identical.

Here are some links that you may find helpful:

- [Documentation on the MQTT Agent](https://docs.aws.amazon.com/freertos/latest/lib-ref/html1/aws__mqtt__agent_8h.html)
- [Documentation on the relevant MQTT v2.x.x APIs](https://docs.aws.amazon.com/freertos/latest/lib-ref/c-sdk/mqtt/mqtt_function_connect.html)
