### ISSUE TITLE
Old state referenced in comments, new function return unclear

### ISSUE THREAD

**Issue by jnz86** [aws/amazon-freertos#2370]
**Describe the bug**
State from comment no longer exists in https://github.com/aws/amazon-freertos/blob/202007.00/libraries/freertos_plus/aws/ota/include/aws_iot_ota_agent.h

**Expected behavior**
Expected state to exist.... does not!

**LINE**
623

**Additional context**
```  * A normal shutdown will return eOTA_AgentState_NotReady. Otherwise, refer to the OTA_State_t enum for details. ```

Thank you!

**Comment by yanjos-dev** [comment]
@jnz86 Thank you for pointing this out, this is a mistake, I created a PR ( #2377 ) to fix this. 

When this function is called, there's a maximum wait time (in ticks) that's passed in. Inside the function, it will send the shutdown event to the OTA agent, then wait until either the OTA Agent is shutdown or the maximum number of ticks has been met. If the agent is shutdown before the maximum number of ticks has been met, the expected state is `eOTA_AgentState_Stopped`. Otherwise it will be the current state of the OTA Agent.
