### ISSUE TITLE
[General] General inquire about development tools and practices

### ISSUE THREAD

**Issue by laszlopataki** [aws/amazon-freertos#3346]
Hi, thank you for the great project. 
I am heavily using AFR code in my project and I was wondering what tools are you guys using to develop freertos? 
- Any auto formatter tool like clang-format?
- IDEs?
- PC-Lint?
- Conda?
- Docker for the build environment or other purposes?
- Naming conventions? 
- Design patterns? 
- Anything else?

**Comment by alfred2g** [comment]
Hello Sorry for the late reply.
I am glad you are enjoying FreeRTOS!

We do use Uncrustify for code formatting, we also have git action to check that  on each PR, you will be able to find examples in .github directory
We do use dockers, and we do have a linux simulator , a windows simulator, and qemu emulation tests as well, you will find them all in the repo: www.github.com/FreeRTOS/FreeRTOS and  www.github.com/FreeRTOS/FreeRTOS-Kernel
We use PC-lint and Coverity as well, various developers use different tools as well.
you will find our naming convention here:  https://freertos.org/fr-content-src/uploads/2018/07/161204_Mastering_the_FreeRTOS_Real_Time_Kernel-A_Hands-On_Tutorial_Guide.pdf 
Data Types and Coding Style Guides, it is a bit outdated, we do use spaces instead of tabs now for example which you will find in the uncrustify config: https://github.com/aws/amazon-freertos/blob/main/tools/uncrustify.cfg
We do have multiple projects with multiple IDE support: Keil / IAR / Code Composer Studio / normal makefiles
