### ISSUE TITLE
[BUG] <Wrong return value in SecureSocketsTransport_Disconnect in transport_secure_sockets.c>

### ISSUE THREAD

**Issue by maa1370** [aws/amazon-freertos#3455]
**Describe the bug**
Please first see #3014 as a refrence. Now consider when a force disconnect happens in code (when running), e.g. connected wifi access point is turned off. in this case SOCKETS_Shutdown fails, but SOCKETS_Close does it works correctly. as mentioned in 3014 [here](https://github.com/aws/amazon-freertos/issues/3014#issuecomment-789228229), "This matches the [shutdown behavior documented here](https://pubs.opengroup.org/onlinepubs/007908799/xns/shutdown.html), and is therefore presumably correct. [Close actually cleans up the resource](https://pubs.opengroup.org/onlinepubs/007908799/xns/close.html), ...".

**System information**
- Hardware board: esp32

**Expected behavior**
SecureSocketsTransport_Disconnect should return succeessfully if shutdown fails but close succeeds. in fact it should just check for close return value since shutdown  return value is not important.

**Solution**
i think:
1- SecureSocketsTransport_Disconnect should return `closeStatus`
2- if 1 is correct, lines below in the function are useless:
`        if( ( shutdownStatus != TRANSPORT_SOCKET_STATUS_SUCCESS ) || ( closeStatus != TRANSPORT_SOCKET_STATUS_SUCCESS ) )
        {
            shutdownStatus = TRANSPORT_SOCKET_STATUS_INTERNAL_ERROR;
        }
`
3- maybe you want to change line below to something else, so it won't be misleading (as user may think the function has failed, although it hasn't)
`            LogError( ( "Failed to close connection: SOCKETS_Shutdown call failed. %d", transportSocketStatus ) );
`

**Some notes**
@lundinc2 , since you have provided the fix for 3104, you may want to check this
@dipen-1337lab, @jsstrandberg, you may want to check this too.

Regards

**Comment by maa1370** [comment]
@dipen-1337lab

**Comment by dipen-1337lab** [comment]
Namaskar @maa1370, 

> I think you should not set returnStatus to TRANSPORT_SOCKET_STATUS_INTERNAL_ERROR since you do not revert it back to TRANSPORT_SOCKET_STATUS_SUCCESS if SOCKETS_Shutdown() fails.

Yes. Actually, there's no point in setting the returnStatus when `SOCKETS_Shutdown()` fails because the `SOCKETS_Close()` always gets called, unconditionally (with reference to my modified code block shared earlier). The success/ failure of SOCKETS_Close() is what really matters. I shall remove that line of code in my application code. Thank you!


> I think a problem can only happen if return value of SecureSocketsTransport_Disconnect is used somewhere in code logic to do something special in case disconnect was not successful, and for these cases the return value should be corrected.

The documentation in the `transport_secure_sockets.h` reads as below for the `TransportSocketStatus` enum.

    TRANSPORT_SOCKET_STATUS_INTERNAL_ERROR,      /**< A call to a system API resulted in an internal error. */

As per my understanding, the `TransportSocketStatus` enum is provided as an abstraction/ wrapper to the code developer instead of using the actual system API return values, which is a good programming practise. In our context, the TRANSPORT_SOCKET_STATUS_INTERNAL_ERROR return value corresponds to the failure of Shutdown and/ or Close Socket-related APIs.

As long as `Close` always follows `Shutdown` ignoring the success/ failure of the latter, I do not feel the need for any code change. Also, as you have rightly mentioned, the User application ought to handle the appropriate return values to avoid an undesired behaviour/ firmware crash.

With that, I would appreciate if Team AFR can provide their say on this discussion.



> About LogError if SOCKETS_Shutdown() fails, i think it is somehow misleading as described in first post, and should be at least changed to LogWarn.

Point taken. Thank you, again. Will correct this in my application code as well.

Thanks | Regards,
Dipen

**Comment by maa1370** [comment]
@dipen-1337lab thanks for response.
sorry, you are right, corrected my previous comment (... revert it back to TRANSPORT_SOCKET_STATUS_SUCCESS if SOCKETS_Close succeeds.)

**Comment by maa1370** [comment]
Thanks. It should be correct after #3468 is merged.
feel free to close the issue when you want.
