### ISSUE TITLE
TI uart_term.h unnecessarily included in Secure Sockets Library

### ISSUE THREAD

**Issue by tombresson** [aws/amazon-freertos#71]
Hi,

Is there a necessity for [`aws_secure_sockets.c`](https://github.com/aws/amazon-freertos/blob/065ac67226356554aeee5d57406259186634cf55/lib/secure_sockets/portable/ti/cc3220_launchpad/aws_secure_sockets.c) to include the TI file [`uart_term.h`](https://github.com/aws/amazon-freertos/blob/master/demos/ti/cc3220_launchpad/common/application_code/ti_code/uart_term.h)? To use the Secure Sockets lib, it requires `uart_term.h` be present in the build environment. It doesn't appear it's actually being used in the library, as my project builds with it commented out. Can it be removed?

https://github.com/aws/amazon-freertos/blob/065ac67226356554aeee5d57406259186634cf55/lib/secure_sockets/portable/ti/cc3220_launchpad/aws_secure_sockets.c#L41

**Comment by yuhui-zheng** [comment]
It looks like this issue has been fixed in aws/amazon-freertos master branch -- [https://github.com/aws/amazon-freertos/blob/master/lib/secure_sockets/portable/ti/cc3220_launchpad/aws_secure_sockets.c](https://github.com/aws/amazon-freertos/blob/master/lib/secure_sockets/portable/ti/cc3220_launchpad/aws_secure_sockets.c)

Thanks again for the feedback, and I'm closing the ticket.
