### ISSUE TITLE
Vulnerability

### ISSUE THREAD

**Issue by dkalog** [aws/amazon-freertos#72]
According to https://blog.zimperium.com/freertos-tcpip-stack-vulnerabilities-put-wide-range-devices-risk-compromise-smart-homes-critical-infrastructure-systems/ there are multiple CVE in the amazon FreeRTOS. Which part of the software is affected ? has this been corrected ?

**Comment by shyamataws** [comment]
Hi dkalog,
   The CVEs listed in the blog post relate to vulnerabilities identified in the FreeRTOS+TCP TCP/IP stack and the Secure Sockets library implementation for FreeRTOS+TCP. We released patches for all identified vulnerabilities on August 22, 2018, as part of Release Version 1.3.2 of this repository. The fixes were also posted to the FreeRTOS kernel repository on SourceForge, and the Amazon FreeRTOS AWS console downloads. We are grateful to the researcher Ori Karliner of Zimperium zLabs, who disclosed these issues to Amazon early.

Version 1.3.2: https://github.com/aws/amazon-freertos/commit/12ea022d0f52df211111a79e0aca1ca7b04639d6

Since Amazon has taken on stewardship of FreeRTOS, we have been adding security measures to proactively identify and fix potential security issues using techniques that include automated checks and penetration testing.

If you discover a potential security issue in this project, we ask that you notify AWS/Amazon Security via our vulnerability reporting page: http://aws.amazon.com/security/vulnerability-reporting/.

Thanks
Shyam
